version: 2

sources:
  - name: staging
    database: de-zoomcamp-411619
    schema: dbt_cadaster_stg

    tables:
      - name: stg_katastriyksus_ext
        external:
          location: 'gs://cadaster_data_bucket/KATASTRIYKSUS.csv'
          options:
            format: csv
            skip_leading_rows: 1
            field_delimiter: ';'
            allow_quoted_newlines: true
        